CREATE DATABASE NATURAL_RESOURCES

USE NATURAL_RESOURCES

-- Table -> Calendar_year_revenue

SELECT * FROM calendar_year_revenue

 

-------------------------------------------------------------------- EDA -----------------------------------------------------------------------------------------------------

-- 1. Data Range

SELECT MAX(Calendar_Year) AS MAX_YEAR FROM calendar_year_revenue   
-- 2023 

SELECT MIN(Calendar_Year) AS MAX_YEAR FROM calendar_year_revenue
-- 2003

-- This dataset contains information from 2003 to 2023, covering 20 years.

-- 2. Land_Class counts
SELECT Land_Class, COUNT(*) AS COUNTS
FROM calendar_year_revenue
GROUP BY Land_Class
ORDER BY COUNTS 
-- Value counts of the Land Class : Native American = 935
--									Federal = 47478

-- 3. Land_Category counts
SELECT Land_Category, COUNT(*) AS COUNTS
FROM calendar_year_revenue
GROUP BY Land_Category
ORDER BY COUNTS 
-- Value counts of the Land Category : Offshore = 947
--									  Onshore = 47399
--									  Not Tied to a Lease = 67

-- 4. States counts
SELECT State, COUNT(*) AS COUNTS
FROM calendar_year_revenue
GROUP BY State
ORDER BY COUNTS 

-- 5. Country counts
SELECT County, COUNT(*) AS COUNTS
FROM calendar_year_revenue
GROUP BY County
ORDER BY COUNTS 

-- 6. FIPS code counts
SELECT  FIPS_Code, COUNT(*) AS COUNTS
FROM calendar_year_revenue
GROUP BY FIPS_Code
ORDER BY COUNTS 

-- 7. Offshore region counts
SELECT Offshore_Region, COUNT(*) AS COUNTS
FROM calendar_year_revenue
GROUP BY Offshore_Region
ORDER BY COUNTS 

-- 8. Revenue type counts
SELECT Revenue_Type, COUNT(*) AS COUNTS
FROM calendar_year_revenue
GROUP BY Revenue_Type
ORDER BY COUNTS 

-- 9. Mineral_lease_type counts
SELECT Mineral_Lease_Type, COUNT(*) AS COUNTS
FROM calendar_year_revenue
GROUP BY Mineral_Lease_Type
ORDER BY COUNTS 

-- 10. Commodity counts
SELECT Commodity, COUNT(*) AS COUNTS
FROM calendar_year_revenue
GROUP BY Commodity
ORDER BY COUNTS 

-- 11. Products count
SELECT Product, COUNT(*) AS COUNTS
FROM calendar_year_revenue
GROUP BY Product
ORDER BY COUNTS 

------------------------------------------------------------------------------------------------------------------------------------------------------

-- Check for nulls

SELECT COUNT(*) AS NULLS FROM calendar_year_revenue
WHERE State IS NULL

SELECT COUNT(*) AS NULLS FROM calendar_year_revenue
WHERE County IS NULL

SELECT COUNT(*) AS NULLS FROM calendar_year_revenue
WHERE FIPS_Code IS NULL

SELECT COUNT(*) AS NULLS FROM calendar_year_revenue
WHERE Offshore_Region IS NULL

SELECT COUNT(*) AS NULLS FROM calendar_year_revenue
WHERE Mineral_Lease_Type IS NULL

SELECT COUNT(*) AS NULLS FROM calendar_year_revenue
WHERE Product IS NULL



----------------------------------------------------------------------------- Analysis---------------------------------------------------------------------------------------------------
--------- DESCRIPTIVE ANALYSIS

-- 1. Total revenue per year / Revenue trends over time
SELECT Calendar_Year, 
SUM(Revenue) AS REVENUE_PER_YEAR 
FROM calendar_year_revenue
GROUP BY Calendar_Year
ORDER BY Calendar_Year



-- 2. Rvenue by Commodity
SELECT Commodity,
SUM(Revenue) AS REVENUE_PER_COMMODITY
FROM calendar_year_revenue
GROUP BY Commodity



-- 3. Revenue generated by state
SELECT State,
SUM(Revenue) AS REVENUE_PER_STATE 
FROM calendar_year_revenue
GROUP BY State
 

-- 4. Top 5 Revenue generating states
SELECT TOP 5
State,
SUM(Revenue) AS REVENUE_PER_STATE 
FROM calendar_year_revenue
GROUP BY State
ORDER BY REVENUE_PER_STATE DESC



-- 5. Annual revenue by Revenue_type
SELECT Revenue_Type,
SUM(Revenue) AS REVENUE_BY_REVENUE_TYPE
FROM calendar_year_revenue
GROUP BY Revenue_Type


-- 6. Revenue distribution by region
SELECT Offshore_Region,
SUM(Revenue) AS REVENUE
FROM calendar_year_revenue
GROUP BY Offshore_Region


-- 7.  Top contributing commodities or states
SELECT TOP 10 Commodity, 
State,
SUM(Revenue) AS REVENUE
FROM calendar_year_revenue
GROUP BY Commodity, State
ORDER BY REVENUE DESC	


-- DIAGNOSTIC ANALYSIS

-- 8. Compare the onshore & offshore revenue
SELECT Land_Category,
SUM(Revenue) AS REVENUE
FROM calendar_year_revenue
GROUP BY Land_Category
ORDER BY REVENUE 


-- 9. Revenue by year & Commodity
SELECT Calendar_Year, Commodity,
SUM(Revenue) AS REVENUE
FROM calendar_year_revenue
GROUP BY Calendar_Year, Commodity 
ORDER BY Calendar_Year
 


-- 10. YOY Chnage (FOR GROWTH)
SELECT Calendar_Year,
Commodity,
SUM(Revenue) AS REVENUE,
LAG(SUM(Revenue)) OVER (PARTITION BY Commodity ORDER BY Calendar_Year) AS PREV_YEAR_REVENUE,
SUM(Revenue) - LAG(SUM(Revenue)) OVER (PARTITION BY Commodity ORDER BY Calendar_Year) AS REVENUE_CHANGE,
CASE
	WHEN LAG(SUM(Revenue)) OVER (PARTITION BY Commodity ORDER BY Calendar_Year) = 0 THEN NULL
	ELSE ROUND (
	(SUM(Revenue) - LAG(SUM(Revenue)) OVER (PARTITION BY Commodity ORDER BY Calendar_Year)) * 100.0 / 
	LAG(SUM(Revenue)) OVER (PARTITION BY Commodity ORDER BY Calendar_Year), 2 )
END AS YOY_CHANGE
FROM calendar_year_revenue
GROUP BY Calendar_Year, Commodity
ORDER BY Commodity, Calendar_Year
 


-- 11. Impact of Different Commodities on Revenue Drop/Growth
WITH REVENUE_BY_YEAR AS (
	SELECT Calendar_Year, Commodity,
	SUM(Revenue) AS REVENUE
	FROM calendar_year_revenue
	GROUP BY Calendar_Year, Commodity
),
REVENUE_CHANGE AS ( 
	SELECT Calendar_Year,
	Commodity,
	REVENUE,
	LAG(REVENUE) OVER (PARTITION BY Commodity ORDER BY Calendar_Year) AS PREV_YEAR_REVENUE,
	(REVENUE - LAG(REVENUE) OVER (PARTITION BY Commodity ORDER BY Calendar_Year) ) AS REVENUE_CHANGE
	FROM REVENUE_BY_YEAR
)

SELECT Calendar_Year,
Commodity,
REVENUE,
PREV_YEAR_REVENUE,
CASE 
	WHEN PREV_YEAR_REVENUE = 0 THEN NULL
	ELSE ROUND (
	(REVENUE - PREV_YEAR_REVENUE) * 100.0 / 
	PREV_YEAR_REVENUE, 2) 
END AS YOY_CHANGE,
CASE 
	WHEN REVENUE > PREV_YEAR_REVENUE THEN 'GROWTH'
	WHEN REVENUE < PREV_YEAR_REVENUE THEN 'DROP'
	ELSE 'NO CHNAGE'
END AS IMPACT
FROM REVENUE_CHANGE
ORDER BY Calendar_Year, Commodity


--12.  Top 5 Products
SELECT TOP 5 Product,
SUM(Revenue) AS Tot_Revenue
FROM calendar_year_revenue
GROUP BY Product
ORDER BY Tot_Revenue DESC

-- 13. Bottom 5 Products by Revenue
SELECT TOP 5 Product,
SUM(Revenue) AS Tot_Revenue
FROM calendar_year_revenue
GROUP BY Product
ORDER BY Tot_Revenue 

-- 13. Impact of offshore vs onshore
-- Total Revenue by Offshore vs Onshore
SELECT Land_Category,
SUM(Revenue) AS REVENUE
FROM calendar_year_revenue
GROUP BY Land_Category
ORDER BY REVENUE DESC



-- 14. Yearly Trend: Offshore vs Onshore
SELECT Calendar_Year,
Land_Category,
SUM(Revenue) AS TOT_REVENUE
FROM calendar_year_revenue
GROUP BY Calendar_Year, Land_Category
ORDER BY Calendar_Year


-- 15.  Share(% Contribution) of Offshore/ Onshore
SELECT Land_Category,
SUM(Revenue) AS TOT_REVENUE,
ROUND(SUM(Revenue) * 100.0 / (SELECT SUM(Revenue) AS OVERALL_REVENUE FROM calendar_year_revenue),2) AS CONTRIBUTION
FROM calendar_year_revenue
GROUP BY Land_Category


-- 16. Categorize the states into high and low revenue (TOP 5 & BOTTOM 5)
WITH TOT_REVENUE AS (
	SELECT State,
	SUM(Revenue) AS TOT_REVENUE
	FROM calendar_year_revenue
	GROUP BY State
), 
RANKED_STATES AS (
	SELECT State,
	TOT_REVENUE,
	RANK() OVER (ORDER BY TOT_REVENUE DESC) AS RANK_DESC,
	RANK() OVER (ORDER BY TOT_REVENUE ASC) AS RANK_ASC
	FROM TOT_REVENUE
),
CLASSIFIED_STATES AS (
	SELECT State,
	TOT_REVENUE,
	CASE 
		WHEN RANK_DESC <= 5 THEN 'HIGH'
		WHEN RANK_ASC <= 5 THEN 'LOW'
		ELSE 'MID'
	END AS REVENUE_GROUP
	FROM RANKED_STATES
)
SELECT * 
FROM CLASSIFIED_STATES
ORDER BY REVENUE_GROUP, TOT_REVENUE DESC


-- PRESCRIPTIVE ANALYSIS

-- 17. Identify states with consistent YoY growth
WITH REVENUE_BY_YEAR AS (
	SELECT Calendar_Year, State,
	SUM(Revenue) AS REVENUE
	FROM calendar_year_revenue
	GROUP BY Calendar_Year, State
),
PREV_YEAR_REVENUE AS ( 
	SELECT Calendar_Year,
	State,
	REVENUE,
	LAG(REVENUE) OVER (PARTITION BY State ORDER BY Calendar_Year) AS PREV_YEAR_REVENUE
	FROM REVENUE_BY_YEAR
),

REVENUE_CHANGE AS ( 
	SELECT Calendar_Year,
	State,
	REVENUE, 
	PREV_YEAR_REVENUE,
	(REVENUE - PREV_YEAR_REVENUE) AS REVENUE_CHANGE
	FROM PREV_YEAR_REVENUE
	WHERE PREV_YEAR_REVENUE IS NOT NULL
),
CONSISTENT_STATE_GROWTH AS (
	SELECT State
	FROM REVENUE_CHANGE
	GROUP BY state
    HAVING MIN(revenue_change) > 0
)
SELECT R.*
FROM REVENUE_CHANGE AS R
JOIN CONSISTENT_STATE_GROWTH AS C 
ON R.state = C.state
ORDER BY R.state, R.Calendar_Year

